[tool.poetry]
name = "sparx_agency"
version = "0.1.0"
description = ""
authors = ["NadavCherry", "Shir Ben Ami", "Daphna Ashkenazi", "Moshe Beutel"]
readme = ["README.md"]

packages = [
    { include = "core", from="sparx_agency"},
    { include = "robots", from="sparx_agency"},
    { include = "tasks", from="sparx_agency"}
]

[tool.poetry.dependencies]
python = "^3.12"
tqdm = "^4.67.1"
pygame = "^2.6.1"
numpy = "^2.3.0"
pandas = "^2.3.0"
matplotlib = "^3.10.3"
seaborn = "^0.13.2"

[tool.poetry.scripts]
benchmark = "sparx_agency.core.planning.evaluation.benchmark_runner:main"
analyze = "sparx_agency.core.planning.evaluation.analyze_results:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
