"""The committed hospital decomposition, checked against the map it came from.

These assert about *data in the repository*, not about an algorithm: the region
map is ground truth that a flight plans over, it is regenerated by hand from an
external world checkout, and the way it goes wrong is by drifting quietly out of
step with the occupancy map beside it. Every number here is one a person would
otherwise have to re-derive to trust the file.
"""
from __future__ import annotations

import os

import numpy as np
import pytest

from sparx_agency.core.planning.exploration.region_map import NO_REGION, RegionMap

_MAPS = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), *([os.pardir] * 4),
    "robots", "SJTU", "maps")
_REGIONS = os.path.join(_MAPS, "hospital_regions.yaml")

pytestmark = pytest.mark.skipif(
    not os.path.isfile(_REGIONS),
    reason="the hospital region map has not been built")


@pytest.fixture(scope="module")
def hospital():
    return RegionMap.load(_REGIONS)


def test_it_is_co_registered_with_the_occupancy_map(hospital):
    """Same grid, same resolution, same origin -- or every pose lands elsewhere."""
    cv2 = pytest.importorskip("cv2")
    from sparx_agency.tasks.planning.sjtu_internvla_n1.map_backdrop import (
        load_map_backdrop,
    )
    backdrop = load_map_backdrop(os.path.join(_MAPS, "hospital.yaml"))
    assert backdrop is not None
    assert hospital.labels.shape == backdrop.occupied_mask.shape
    assert hospital.resolution == pytest.approx(backdrop.resolution)
    assert hospital.origin_x == pytest.approx(backdrop.origin_x)
    assert hospital.origin_y == pytest.approx(backdrop.origin_y)


def test_the_building_it_describes_is_the_one_the_coverage_counts(hospital):
    """The regions must tile the same floor coverage divides by: 1140 m2."""
    cell = hospital.resolution ** 2
    total = float((hospital.labels != NO_REGION).sum() * cell)
    assert total == pytest.approx(1139.9, abs=2.0)
    assert sum(r.area_m2 for r in hospital.regions.values()) == pytest.approx(
        total, abs=1.0)


def test_it_holds_the_rooms_and_corridors_the_hospital_has(hospital):
    assert len(hospital.rooms()) == 20
    assert len(hospital.corridors()) == 7
    assert len(hospital.portals) == 33


def test_no_room_is_sealed(hospital):
    """A room with no opening is one no flight could ever clear."""
    sealed = [r.name for r in hospital.rooms() if not r.portals]
    assert sealed == []


def test_every_room_has_a_doorway_the_airframe_could_pass(hospital):
    """0.63 m wide, and this building's doors are 0.90 and 1.45 m."""
    for room in hospital.rooms():
        widest = max(p.width_m for p in hospital.portals_of(room.id))
        assert widest >= 0.85, "%s has only %.2f m" % (room.name, widest)


def test_the_doorway_widths_are_the_ones_the_world_has(hospital):
    """Two sizes, and nothing in between -- a decomposition that had smeared
    the openings would show a spread instead."""
    room_doors = sorted({round(p.width_m, 2)
                         for room in hospital.rooms()
                         for p in hospital.portals_of(room.id)})
    assert room_doors == [0.90, 1.45]


def test_every_portal_is_a_Portal2D_the_behaviours_can_already_use(hospital):
    """Not a second description of a doorway -- the shared one, plus its edge."""
    from sparx_agency.core.common.types.semantics import Portal2D
    for portal in hospital.portals.values():
        assert isinstance(portal, Portal2D)
        assert portal.width_m > 0.0
        assert portal.normal_yaw is not None


#: An opening wider than this is not a doorway but a room running into another
#: room. Its boundary is a long line rather than a gap, so "the direction you
#: cross it" is not a property it has -- the 24.75 m mouth where this building's
#: south hall meets its corridor is the only one, and nothing aims through it.
DOORWAY_MAX_M = 3.0


def test_every_doorway_normal_points_at_the_far_region(hospital):
    """``EnterPortalBehavior`` builds approach and cross waypoints from it, so a
    normal facing the wrong way would aim the approach through the wall."""
    import math
    doorways = [p for p in hospital.portals.values() if p.width_m <= DOORWAY_MAX_M]
    assert len(doorways) >= 28, "the building's real openings"
    for portal in doorways:
        first, second = portal.between
        # Just across the threshold. A longer step can leave the far region
        # entirely -- several of these doorways sit within a metre of where one
        # corridor stretch is cut from the next.
        step = 0.15
        ahead = (portal.centre[0] + step * math.cos(portal.normal_yaw),
                 portal.centre[1] + step * math.sin(portal.normal_yaw))
        behind = (portal.centre[0] - step * math.cos(portal.normal_yaw),
                  portal.centre[1] - step * math.sin(portal.normal_yaw))
        front = hospital.region_at(*ahead)
        back = hospital.region_at(*behind)
        assert front is not None and back is not None, portal.id
        assert {front.id, back.id} == {first, second}, (
            "portal %s normal does not cross from %d to %d"
            % (portal.id, first, second))
        assert front.id == second, "the normal points from the lower id to the higher"


def test_the_wide_junctions_are_still_well_formed(hospital):
    """They carry a normal like anything else; it just is not worth aiming by."""
    for portal in hospital.portals.values():
        if portal.width_m <= DOORWAY_MAX_M:
            continue
        assert portal.normal_yaw is not None
        assert hospital.region_at(*portal.centre) is not None
        assert len(set(portal.between)) == 2


def test_every_region_centre_is_inside_its_own_region(hospital):
    """The centre is used to aim the aircraft, so it has to be a place."""
    for region in hospital.regions.values():
        found = hospital.region_at(*region.centre)
        assert found is not None and found.id == region.id, region.name


def test_the_named_start_areas_all_land_in_a_region(hospital):
    """Every pose a campaign ferries to must have somewhere to be."""
    yaml = pytest.importorskip("yaml")
    areas_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              os.pardir, "config", "hospital_areas.yaml")
    areas = (yaml.safe_load(open(areas_path)) or {}).get("areas", {})
    assert areas, "no start areas to check"
    for name, spec in areas.items():
        region = hospital.region_at(float(spec["x"]), float(spec["y"]))
        assert region is not None, "%s is outside the building" % name


def test_the_corridors_are_connected_to_each_other(hospital):
    """A circulation network in pieces would strand half the checklist."""
    corridors = {r.id for r in hospital.corridors()}
    start = next(iter(corridors))
    seen, frontier = {start}, [start]
    while frontier:
        rid = frontier.pop()
        for neighbour, _ in hospital.neighbours(rid):
            if neighbour.id in corridors and neighbour.id not in seen:
                seen.add(neighbour.id)
                frontier.append(neighbour.id)
    assert seen == corridors


def test_every_room_reaches_a_corridor(hospital):
    for room in hospital.rooms():
        kinds = {r.kind for r, _ in hospital.neighbours(room.id)}
        assert "corridor" in kinds, room.name
