"""Turn recorded contact-hold episodes into a hazard file the planner can avoid.

The aircraft gets **held** against geometry — tilted, airborne and rigid — in
about 36 % of flights, and it is not spread over the map: half the episodes
happen in **8** two-metre cells and the top **12** hold 68 % of the lost time,
one of them trapping the aircraft on 46 separate flights (LOOP_BUGS.md B33).
Repeat visits within a single flight are only 21 % of the loss, so a per-flight
memory cannot fix this; the knowledge has to outlive the flight. This module
writes that knowledge down.

Ranking is by **seconds lost**, not by episode count, because a cell that traps
the aircraft once for two minutes costs more than one that brushes it ten times.

The file records the map name and the cell size it was built for. Coordinates
are only meaningful in the localization frame of that map, and a map-epoch
change invalidates them silently — the consumer must refuse a file whose
``map`` does not match the map being flown.

Usage, from the repo root::

    PYTHONPATH=. .venv/bin/python -m sparx_agency.tools.falcon_campaign.hazard_map \\
        --episodes runs/_analysis/contact_holds.jsonl --top 12
"""
from __future__ import annotations

import argparse
import collections
import json
import math
from pathlib import Path

from sparx_agency.tools.falcon_campaign import config as C

#: Side of the square cell episodes are binned into, metres. Two metres is a
#: little over a drone-width plus the 0.4 m inflation, so one cell is "the spot
#: that trapped it" rather than a point the aircraft would have to hit exactly.
CELL_M = 2.0


def rank_cells(episodes, cell_m=CELL_M):
    """Group episodes into cells and rank them by seconds lost.

    Args:
        episodes: Episode dicts from ``contact_hold_survey``.
        cell_m: Cell side, metres.

    Returns:
        A list of cell dicts, worst first.
    """
    held = collections.Counter()
    count = collections.Counter()
    flights = collections.defaultdict(set)
    for e in episodes:
        if e.get("x") is None or e.get("y") is None:
            continue
        key = (math.floor(e["x"] / cell_m) * cell_m,
               math.floor(e["y"] / cell_m) * cell_m)
        held[key] += e.get("duration_s") or 0.0
        count[key] += 1
        flights[key].add(e.get("run"))
    out = []
    for key, seconds in held.most_common():
        out.append(dict(x=key[0] + cell_m / 2.0, y=key[1] + cell_m / 2.0,
                        held_s=round(seconds, 1), episodes=count[key],
                        flights=len(flights[key])))
    return out


def build(episodes, top, cell_m=CELL_M, map_name=None):
    """Build the hazard file's contents.

    Args:
        episodes: Episode dicts.
        top: How many worst cells to keep.
        cell_m: Cell side, metres.
        map_name: Map these coordinates belong to; defaults to the campaign's.

    Returns:
        The hazard document as a dict.
    """
    ranked = rank_cells(episodes, cell_m)
    kept = ranked[:top]
    total = sum(c["held_s"] for c in ranked) or 1.0
    return dict(
        map=map_name or C.MAP_NAME,
        frame="localization",
        cell_m=cell_m,
        built_from_episodes=len(episodes),
        cells_total=len(ranked),
        cells_kept=len(kept),
        covers_frac_of_held_time=round(sum(c["held_s"] for c in kept) / total, 3),
        hazards=kept)


def as_blocked_regions(doc, z):
    """Flatten the hazard cells into FALCON's blocked-regions parameter form.

    ``frontier_finder.cpp`` reads ``/frontier_finder/blocked_regions_runtime``
    at construction as a flat list of ``x, y, z`` triples and retires every
    frontier within ``blocked_region_radius`` of each. Seeding it means FALCON
    starts the flight already knowing not to route into the places that have
    wedged the aircraft, instead of rediscovering each one at the cost of a
    flight (LOOP_FIXES.md F21).

    Args:
        doc: A hazard document from :func:`build`.
        z: Height to place the regions at, metres. The cells are a 2D result;
            the planner's check is a 3D radius, so this should be the altitude
            the aircraft actually flies at.

    Returns:
        A flat list of floats, ``[x0, y0, z0, x1, y1, z1, ...]``.
    """
    flat = []
    for cell in doc["hazards"]:
        flat.extend([round(cell["x"], 3), round(cell["y"], 3), float(z)])
    return flat


def write_seed_yaml(doc, path, z):
    """Write the blocked-regions seed as a roslaunch-loadable YAML file.

    Args:
        doc: A hazard document from :func:`build`.
        path: Destination file.
        z: Height to place the regions at, metres.

    Returns:
        The flat list that was written.
    """
    flat = as_blocked_regions(doc, z)
    lines = [
        "# GENERATED by tools/falcon_campaign/hazard_map.py -- do not hand-edit.",
        "# Seeds FALCON's frontier blocked-regions from %d recorded contact-hold"
        % doc["built_from_episodes"],
        "# episodes: the %d cells below hold %.0f%% of all the time the"
        % (doc["cells_kept"], 100.0 * doc["covers_frac_of_held_time"]),
        "# aircraft has spent wedged against geometry (LOOP_BUGS.md B33).",
        "# Coordinates are the %s map's localization frame; a map change makes"
        % doc["map"],
        "# them silently meaningless.",
        "frontier_finder:",
        "  blocked_regions_runtime: [%s]"
        % ", ".join("%.3f" % v for v in flat),
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return flat


def main(argv=None):
    """Write the hazard file and report what it covers."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--episodes", type=Path,
                    default=Path("runs/_analysis/contact_holds.jsonl"))
    ap.add_argument("--out", type=Path,
                    default=Path("runs/_analysis/hazard_map.json"))
    ap.add_argument("--top", type=int, default=12)
    ap.add_argument("--cell", type=float, default=CELL_M)
    ap.add_argument("--seed-yaml", type=Path, default=None,
                    help="also write a roslaunch-loadable blocked-regions seed")
    ap.add_argument("--seed-z", type=float, default=1.3,
                    help="height to place the seeded regions at, metres")
    args = ap.parse_args(argv)

    episodes = []
    with args.episodes.open() as fh:
        for line in fh:
            try:
                episodes.append(json.loads(line))
            except ValueError:
                continue
    doc = build(episodes, args.top, args.cell)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2) + "\n")

    print("map %s, %d episodes -> %d cells, keeping the worst %d"
          % (doc["map"], doc["built_from_episodes"], doc["cells_total"],
             doc["cells_kept"]))
    print("those cover %.0f%% of all time lost to being held"
          % (100.0 * doc["covers_frac_of_held_time"]))
    for c in doc["hazards"]:
        print("   (%7.1f,%7.1f)  %6.0f s  %3d episodes  %3d flights"
              % (c["x"], c["y"], c["held_s"], c["episodes"], c["flights"]))
    print("written: %s" % args.out)
    if args.seed_yaml is not None:
        flat = write_seed_yaml(doc, args.seed_yaml, args.seed_z)
        print("seed:    %s  (%d regions at z=%.2f m)"
              % (args.seed_yaml, len(flat) // 3, args.seed_z))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
