version: '3.8'

services:
  dev_x86:
    build:
      context: .
      dockerfile: Dockerfile.dev-x86
    image: owl-dev-x86
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        limits:
          memory: 8g
    volumes:
      - .:/workspace
    command: python3 run_owl.py

  test_arm64:
    build:
      context: .
      dockerfile: Dockerfile.test-arm64
    image: owl-arm64
    deploy:
      resources:
        limits:
          memory: 8g
    volumes:
      - .:/workspace
    command: python3 run_owl.py
