# Use the official NVIDIA CUDA image with Ubuntu 22.04 as the base image
FROM nvidia-base-cuda-11.7.1-ubuntu-22.04:1.0

# Set environment variables
ENV LD_LIBRARY_PATH /opt/conda/envs/aerialgym/lib
ENV VK_ICD_FILENAMES /usr/share/vulkan/icd.d/nvidia_icd.json

RUN apt-get update 

# # Install Miniconda
# RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
#     bash /miniconda.sh -b -p /opt/conda && \
#     rm /miniconda.sh

# # Add conda to PATH
# ENV PATH /opt/conda/bin:$PATH

# # Create and activate conda environment
# RUN conda create -y -n aerialgym python=3.8 && \
#     echo "source activate aerialgym" > ~/.bashrc
# ENV CONDA_DEFAULT_ENV aerialgym
# ENV PATH /opt/conda/envs/aerialgym/bin:$PATH

# # Install dependencies
# RUN conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 \
#     pytorch-cuda=11.7 -c pytorch -c conda-forge -c defaults && \
#     conda install pyyaml==6.0 tensorboard==2.13.0 -c conda-forge -c pytorch -c defaults && \
#     conda install -c fvcore -c iopath -c conda-forge fvcore iopath && \
#     conda install -c pytorch3d pytorch3d

RUN pip3 install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 tensorboard==2.13.0 pyyaml==6.0 fvcore iopath 
RUN pip3 install "git+https://github.com/facebookresearch/pytorch3d.git"


# Download and install Isaac Gym
RUN https://developer.nvidia.com/isaac-gym-preview-4 && \
    tar -xzf IsaacGym_Preview_4_Package.tar.gz -C /root && \
    rm IsaacGym_Preview_4_Package.tar.gz
WORKDIR /root/isaacgym/python
RUN pip3 install -e .

# Set environment variables for Isaac Gym
RUN echo "export LD_LIBRARY_PATH=/opt/conda/envs/aerialgym/lib" >> ~/.bashrc && \
    echo "export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json" >> ~/.bashrc

# Create workspace directory and install urdfpy package
RUN mkdir -p ~/workspaces/aerial_gym_ws/src && \
    cd ~/workspaces/aerial_gym_ws/src && \
    git clone https://github.com/mmatl/urdfpy.git && \
    cd urdfpy && \
    pip3 install -e .

# Install Aerial Gym Simulator
RUN cd ~/workspaces/aerial_gym_ws/src && \
    git clone https://github.com/ntnu-arl/aerial_gym_simulator.git && \
    cd aerial_gym_simulator && \
    pip3 install -e .
    
ENV TERM=xterm-color

WORKDIR /root

CMD ["bash"]
