#!/usr/bin/env python3
from __future__ import annotations

from collections import deque
import json
import math
import os
from typing import Deque, Dict, Optional, Tuple, Any
from pathlib import Path

import cv2
import numpy as np
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
from sensor_msgs.msg import Image
from geometry_msgs.msg import Vector3Stamped, Twist, PoseStamped
from cv_bridge import CvBridge
import yaml
import csv

from sparx_agency.tasks.localization.common.optical_flow_tracker import OpticalFlowTracker


class FlowDepthVelocityNode(Node):
    """
    Flow + Depth velocity node with delayed-depth support.

    Architecture:
      1. RGB callback runs immediately when an RGB frame arrives.
         It computes Optical Flow in pixel space using consecutive RGB frames.
         The flow result is stored in pending_flow_queue.

      2. Depth callback runs when a Depth frame arrives, possibly later than RGB.
         It finds the matching pending Optical Flow result and converts the
         pixel motion to metric velocity using the Depth map.

    Why this is useful:
      - RGB can be faster than Depth.
      - Depth may be generated by a model and arrive with latency.
      - We do not want ApproximateTimeSynchronizer to block RGB processing.
    """

    def __init__(self):
        super().__init__("flow_depth_velocity_node")

        # Keep the same default behavior as your current scripts.
        self.set_parameters([
            rclpy.parameter.Parameter(
                "use_sim_time",
                rclpy.parameter.Parameter.Type.BOOL,
                True,
            )
        ])

        # ============================================================
        # Parameters
        # ============================================================
        self.declare_parameter("image_topic", "/simple_drone/front/image_raw")
        self.declare_parameter("depth_topic", "/depth_anything/depth")
        self.declare_parameter("output_topic", "/flow_depth/velocity")
        self.declare_parameter("pose_est_topic", "/flow_depth/pose_est")
        self.declare_parameter("gt_vel_topic", "/simple_drone/gt_vel")

        self.declare_parameter(
            "camera_config_yaml",
            str(Path.home() / "GIT/TheAgency/sparx_agency/robots/XTEND/config/camera_xtend_ros_calib_720_420.yaml")
        )

        self.declare_parameter("camera_frame", "xtend_camera")

        # Visual debug opens an OpenCV window. Keep it disabled by default.
        self.declare_parameter("show_debug", False)

        # Text debug prints velocity and synchronization diagnostics to the ROS log.
        # This is useful on a robot/server where cv2.imshow is not available.
        self.declare_parameter("print_velocity_debug", True)
        self.declare_parameter("velocity_debug_every_n", 1)
        self.declare_parameter("print_flow_queue_debug", True)
        self.declare_parameter("flow_queue_debug_every_n", 30)

        self.declare_parameter("max_corners", 300)
        self.declare_parameter("min_corners", 70)
        self.declare_parameter("lk_win", 21)
        self.declare_parameter("lk_levels", 3)

        self.declare_parameter("min_depth", 0.05)
        self.declare_parameter("max_depth", 10.0)
        self.declare_parameter("depth_scale", 1.0)
        # Reduced EMA alpha from 0.15 to 0.05 to reduce lag between features and smoothed depth
        self.declare_parameter("depth_ema_alpha", 0.05)

        # Manual matching parameters.
        # max_wait_for_depth_sec: maximum accepted time difference between the
        # current RGB/flow timestamp and the Depth timestamp.
        # Reduced from 0.5 to 0.1 to avoid feature staleness and desynchronization.
        self.declare_parameter("max_wait_for_depth_sec", 0.1)

        # Sometimes the Depth header stamp may be a few ms earlier than the RGB
        # stamp because of timestamp jitter. Allow a small negative difference.
        self.declare_parameter("allow_depth_before_flow_sec", 0.03)

        # Queue size for pending optical-flow results waiting for Depth.
        self.declare_parameter("flow_queue_size", 200)

        # Matching time mode:
        #   "stamp"   -> match by msg.header.stamp. Best if Depth preserves RGB stamp.
        #   "arrival" -> match by callback arrival time. Useful if Depth header stamp is
        #                the delayed publication time or not reliable.
        self.declare_parameter("sync_time_mode", "stamp")

        # If True, save a copy of RGB frame with each flow result for debug drawing.
        # This costs memory, so it is only needed when show_debug=True.
        self.declare_parameter("store_debug_frames", True)

        self.declare_parameter(
            "json_out_path",
            str(Path.home() / "GIT/TheAgency/sparx_agency/tasks/localization/ros2/depth_optical/csv_eval/estimated_trajectory.json"),
        )

        self.declare_parameter("log_vel_csv_path", "/tmp/velocity_log.csv")
        self.declare_parameter("log_pose_csv_path", "/tmp/pose_log.csv")

        self.vel_csv_path = self.get_parameter("log_vel_csv_path").get_parameter_value().string_value
        self.pose_csv_path = self.get_parameter("log_pose_csv_path").get_parameter_value().string_value

        self.vel_log_file = open(self.vel_csv_path, 'w', newline='')
        self.vel_csv_writer = csv.writer(self.vel_log_file)
        self.vel_csv_writer.writerow([
            'timestamp', 'dt', 
            #'raw_vx', 'raw_vy', 'raw_vz', 
            #'filtered_vx', 'filtered_vy', 'filtered_vz', 
            'pub_vx', 'pub_vy', 'pub_vz', 
            'features_used'
        ])

        self.pose_log_file = open(self.pose_csv_path, 'w', newline='')
        self.pose_csv_writer = csv.writer(self.pose_log_file)
        self.pose_csv_writer.writerow(['timestamp', 'x', 'y', 'z'])

        # ============================================================
        # Read parameters
        # ============================================================
        self.image_topic = self.get_parameter("image_topic").get_parameter_value().string_value
        self.depth_topic = self.get_parameter("depth_topic").get_parameter_value().string_value
        self.output_topic = self.get_parameter("output_topic").get_parameter_value().string_value
        self.pose_est_topic = self.get_parameter("pose_est_topic").get_parameter_value().string_value
        self.gt_vel_topic = self.get_parameter("gt_vel_topic").get_parameter_value().string_value
        self.camera_config_yaml = self.get_parameter("camera_config_yaml").get_parameter_value().string_value

        self.camera_frame = self.get_parameter("camera_frame").get_parameter_value().string_value
        self.show_debug = bool(self.get_parameter("show_debug").get_parameter_value().bool_value)

        self.print_velocity_debug = bool(
            self.get_parameter("print_velocity_debug").get_parameter_value().bool_value
        )
        self.velocity_debug_every_n = max(
            1,
            int(self.get_parameter("velocity_debug_every_n").get_parameter_value().integer_value),
        )
        self.print_flow_queue_debug = bool(
            self.get_parameter("print_flow_queue_debug").get_parameter_value().bool_value
        )
        self.flow_queue_debug_every_n = max(
            1,
            int(self.get_parameter("flow_queue_debug_every_n").get_parameter_value().integer_value),
        )

        self.max_corners = int(self.get_parameter("max_corners").get_parameter_value().integer_value)
        self.min_corners = int(self.get_parameter("min_corners").get_parameter_value().integer_value)
        lk_win = int(self.get_parameter("lk_win").get_parameter_value().integer_value)
        lk_levels = int(self.get_parameter("lk_levels").get_parameter_value().integer_value)

        self.min_depth = float(self.get_parameter("min_depth").get_parameter_value().double_value)
        self.max_depth = float(self.get_parameter("max_depth").get_parameter_value().double_value)
        self.depth_scale = float(self.get_parameter("depth_scale").get_parameter_value().double_value)
        self.ema_alpha = float(self.get_parameter("depth_ema_alpha").get_parameter_value().double_value)

        self.max_wait_for_depth_sec = float(
            self.get_parameter("max_wait_for_depth_sec").get_parameter_value().double_value
        )
        self.allow_depth_before_flow_sec = float(
            self.get_parameter("allow_depth_before_flow_sec").get_parameter_value().double_value
        )
        flow_queue_size = int(self.get_parameter("flow_queue_size").get_parameter_value().integer_value)

        self.sync_time_mode = self.get_parameter("sync_time_mode").get_parameter_value().string_value.strip().lower()
        if self.sync_time_mode not in ("stamp", "arrival"):
            self.get_logger().warn(
                f"Invalid sync_time_mode='{self.sync_time_mode}', falling back to 'stamp'"
            )
            self.sync_time_mode = "stamp"

        self.store_debug_frames = bool(
            self.get_parameter("store_debug_frames").get_parameter_value().bool_value
        )
        self.json_out_path = self.get_parameter("json_out_path").get_parameter_value().string_value

        # ============================================================
        # State
        # ============================================================
        self.bridge = CvBridge()
        self.fx: Optional[float] = None
        self.fy: Optional[float] = None
        self.cx: Optional[float] = None
        self.cy: Optional[float] = None

        self.last_smoothed_depth: Optional[np.ndarray] = None
        self.center_depth = 0.0

        self.pending_flow_queue: Deque[Dict[str, Any]] = deque(maxlen=flow_queue_size)

        self.prev_vx = 0.0
        self.prev_vy = 0.0
        self.prev_vz = 0.0
        self.vel_alpha = 0.2

        self.latest_gt_vx = 0.0
        self.latest_gt_vy = 0.0
        self.latest_gt_vz = 0.0

        self.debug_path = [(0.0, 0.0)]
        self.current_distance = 0.0
        self.trajectory_history = []

        self.rgb_count = 0
        self.flow_count = 0
        self.depth_count = 0
        self.published_count = 0
        self.dropped_old_flow_count = 0
        self.no_flow_for_depth_count = 0
        self.no_match_count = 0

        # ============================================================
        # Camera intrinsics and tracker
        # ============================================================
        self.load_camera_intrinsics_from_yaml(self.camera_config_yaml)

        self.tracker = OpticalFlowTracker(
            max_corners=self.max_corners,
            min_corners=self.min_corners,
            lk_win=lk_win,
            lk_levels=lk_levels,
        )

        # BEST_EFFORT is usually correct for camera/image topics, especially
        # in simulation or when publisher uses sensor-data QoS.
        image_qos = QoSProfile(
            history=HistoryPolicy.KEEP_LAST,
            depth=5,
            reliability=ReliabilityPolicy.BEST_EFFORT,
        )

        # ============================================================
        # ROS interfaces
        # ============================================================
        self.vel_pub = self.create_publisher(Vector3Stamped, self.output_topic, image_qos)

        self.rgb_sub = self.create_subscription(
            Image,
            self.image_topic,
            self.rgb_callback,
            image_qos,
        )

        self.depth_sub = self.create_subscription(
            Image,
            self.depth_topic,
            self.depth_callback,
            image_qos,
        )

        self.create_subscription(
            Twist,
            self.gt_vel_topic,
            self.gt_vel_callback,
            image_qos,
        )

        self.pose_sub = self.create_subscription(
            PoseStamped,
            self.pose_est_topic,
            self.pose_est_callback,
            image_qos,
        )

        self.get_logger().info("============================================================")
        self.get_logger().info("[FlowDepth] Started: RGB computes Flow now, Depth completes metric velocity later")
        self.get_logger().info(f"[FlowDepth] RGB topic: {self.image_topic}")
        self.get_logger().info(f"[FlowDepth] Depth topic: {self.depth_topic}")
        self.get_logger().info(f"[FlowDepth] Output topic: {self.output_topic}")
        self.get_logger().info(f"[FlowDepth] sync_time_mode: {self.sync_time_mode}")
        self.get_logger().info(f"[FlowDepth] max_wait_for_depth_sec: {self.max_wait_for_depth_sec:.3f}")
        self.get_logger().info(f"[FlowDepth] allow_depth_before_flow_sec: {self.allow_depth_before_flow_sec:.3f}")
        self.get_logger().info(f"[FlowDepth] flow_queue_size: {flow_queue_size}")
        self.get_logger().info(f"[FlowDepth] print_velocity_debug: {self.print_velocity_debug}")
        self.get_logger().info(f"[FlowDepth] velocity_debug_every_n: {self.velocity_debug_every_n}")
        self.get_logger().info("============================================================")

    # ============================================================
    # Time helpers
    # ============================================================
    @staticmethod
    def stamp_to_sec(stamp) -> float:
        return float(stamp.sec) + float(stamp.nanosec) * 1e-9

    def now_sec(self) -> float:
        now_msg = self.get_clock().now().to_msg()
        return self.stamp_to_sec(now_msg)

    def get_match_time(self, msg: Image, arrival_time_sec: float) -> float:
        if self.sync_time_mode == "arrival":
            return arrival_time_sec
        return self.stamp_to_sec(msg.header.stamp)

    # ============================================================
    # Camera intrinsics
    # ============================================================
    def load_camera_intrinsics_from_yaml(self, yaml_path: str):
        if not os.path.exists(yaml_path):
            raise FileNotFoundError(f"Camera YAML not found: {yaml_path}")

        with open(yaml_path, "r") as f:
            cfg = yaml.safe_load(f)

        # Prefer projection_matrix P, because it is the effective pinhole model
        # after rectification / undistortion.
        if "projection_matrix" in cfg and "data" in cfg["projection_matrix"]:
            P = cfg["projection_matrix"]["data"]
            if len(P) < 12 or P[0] == 0.0:
                raise ValueError(f"Invalid projection_matrix in YAML: {yaml_path}")

            self.fx = float(P[0])
            self.fy = float(P[5])
            self.cx = float(P[2])
            self.cy = float(P[6])

            self.get_logger().info(
                f"[Camera YAML] Loaded projection_matrix: "
                f"fx={self.fx:.2f}, fy={self.fy:.2f}, "
                f"cx={self.cx:.2f}, cy={self.cy:.2f}"
            )
            return

        required = ["fx", "fy", "cx", "cy"]
        if all(k in cfg for k in required):
            self.fx = float(cfg["fx"])
            self.fy = float(cfg["fy"])
            self.cx = float(cfg["cx"])
            self.cy = float(cfg["cy"])

            self.get_logger().info(
                f"[Camera YAML] Loaded raw intrinsics: "
                f"fx={self.fx:.2f}, fy={self.fy:.2f}, "
                f"cx={self.cx:.2f}, cy={self.cy:.2f}"
            )
            return

        raise ValueError(
            f"Could not find projection_matrix or fx/fy/cx/cy in YAML: {yaml_path}"
        )
    # ============================================================
    # RGB callback: compute Optical Flow immediately
    # ============================================================
    def rgb_callback(self, rgb_msg: Image):
        self.rgb_count += 1
        arrival_time_sec = self.now_sec()

        if self.fx is None or self.fy is None:
            return

        try:
            frame = self.bridge.imgmsg_to_cv2(rgb_msg, desired_encoding="bgr8")
        except Exception as e:
            self.get_logger().error(f"[RGB] Convert failed: {e}")
            return

        # Optical Flow is computed immediately, using RGB sequence only.
        flow_res = self.tracker.process(frame, rgb_msg.header.stamp)

        # First frame usually initializes the tracker and returns None.
        if flow_res is None:
            return

        if flow_res.dt <= 0.0:
            self.get_logger().warn(f"[RGB] Invalid optical-flow dt={flow_res.dt}")
            return

        rgb_stamp_sec = self.stamp_to_sec(rgb_msg.header.stamp)
        match_time_sec = self.get_match_time(rgb_msg, arrival_time_sec)

        # Store only the information needed later for metric conversion.
        # good_new pixel coordinates represent the current RGB frame, so the matching
        # Depth should correspond to this RGB frame.
        flow_item = {
            "rgb_stamp": rgb_msg.header.stamp,
            "rgb_stamp_sec": rgb_stamp_sec,
            "rgb_arrival_sec": arrival_time_sec,
            "match_time_sec": match_time_sec,
            "good_old": flow_res.good_old.copy(),
            "good_new": flow_res.good_new.copy(),
            "dt": float(flow_res.dt),
            "frame": frame.copy() if (self.show_debug and self.store_debug_frames) else None,
        }

        self.pending_flow_queue.append(flow_item)
        self.flow_count += 1

        if self.print_flow_queue_debug and self.flow_count % self.flow_queue_debug_every_n == 0:
            self.get_logger().info(
                f"[RGB->Flow] rgb_count={self.rgb_count}, flow_count={self.flow_count}, "
                f"pending_flow={len(self.pending_flow_queue)}, dt={flow_res.dt:.4f}s"
            )

    # ============================================================
    # Depth callback: match Depth to pending Flow and publish velocity
    # ============================================================
    def depth_callback(self, depth_msg: Image):
        self.depth_count += 1
        arrival_time_sec = self.now_sec()

        if self.fx is None or self.fy is None:
            return

        if len(self.pending_flow_queue) == 0:
            self.no_flow_for_depth_count += 1
            if self.no_flow_for_depth_count % 20 == 1:
                self.get_logger().warn("[Depth] Depth arrived but no pending Flow exists yet")
            return

        try:
            depth_cv = self.bridge.imgmsg_to_cv2(depth_msg, desired_encoding="32FC1")
        except Exception as e:
            self.get_logger().error(f"[Depth] Convert failed: {e}")
            return

        raw_depth = np.asarray(depth_cv, dtype=np.float32)
        depth_map = self.smooth_depth_map(raw_depth)
        self.update_center_depth(depth_map)

        depth_stamp_sec = self.stamp_to_sec(depth_msg.header.stamp)
        depth_match_time_sec = self.get_match_time(depth_msg, arrival_time_sec)

        best_flow, age_sec = self.find_best_flow_for_depth(depth_match_time_sec)
        if best_flow is None:
            self.no_match_count += 1
            if self.no_match_count % 20 == 1:
                self.get_logger().warn(
                    f"[Depth] No matching Flow found. "
                    f"pending={len(self.pending_flow_queue)}, depth_count={self.depth_count}"
                )
            return

        self.remove_flows_until_selected(best_flow)

        self.process_flow_with_depth(
            flow_item=best_flow,
            depth_map=depth_map,
            depth_stamp_sec=depth_stamp_sec,
            depth_arrival_sec=arrival_time_sec,
            match_age_sec=age_sec,
        )

    def find_best_flow_for_depth(self, depth_match_time_sec: float) -> Tuple[Optional[Dict[str, Any]], Optional[float]]:
        """
        Find the best pending flow for the current Depth.

        We prefer a flow whose RGB time is before the Depth time, because the Depth
        arrives after RGB. Still, we allow a small negative age for timestamp jitter:

            age = depth_time - flow_time

        Accepted range:
            -allow_depth_before_flow_sec <= age <= max_wait_for_depth_sec
        """
        # Drop flows that are definitely too old for this Depth.
        while len(self.pending_flow_queue) > 0:
            oldest = self.pending_flow_queue[0]
            oldest_age = depth_match_time_sec - oldest["match_time_sec"]

            if oldest_age > self.max_wait_for_depth_sec:
                self.pending_flow_queue.popleft()
                self.dropped_old_flow_count += 1
                if self.dropped_old_flow_count % 20 == 1:
                    self.get_logger().warn(
                        f"[ManualSync] Dropped old Flow. "
                        f"depth-flow age={oldest_age * 1000.0:.1f} ms, "
                        f"dropped_total={self.dropped_old_flow_count}"
                    )
            else:
                break

        if len(self.pending_flow_queue) == 0:
            return None, None

        candidates = []
        for item in self.pending_flow_queue:
            age = depth_match_time_sec - item["match_time_sec"]
            if -self.allow_depth_before_flow_sec <= age <= self.max_wait_for_depth_sec:
                candidates.append((item, age))

        if not candidates:
            return None, None

        # Choose the closest match by absolute time difference.
        best_item, best_age = min(candidates, key=lambda pair: abs(pair[1]))
        return best_item, best_age

    def remove_flows_until_selected(self, selected_flow: Dict[str, Any]):
        """
        Remove all older flows up to the selected flow.
        This prevents publishing the same flow more than once and keeps the queue clean.
        """
        while len(self.pending_flow_queue) > 0:
            item = self.pending_flow_queue.popleft()
            if item is selected_flow:
                break

    # ============================================================
    # Flow + Depth processing
    # ============================================================
    def process_flow_with_depth(
        self,
        flow_item: Dict[str, Any],
        depth_map: np.ndarray,
        depth_stamp_sec: float,
        depth_arrival_sec: float,
        match_age_sec: float,
    ):
        good_old = flow_item["good_old"]
        good_new = flow_item["good_new"]
        dt = flow_item["dt"]
        rgb_stamp = flow_item["rgb_stamp"]

        raw_vx_mps, raw_vy_mps, raw_vz_mps, n_used = self.velocity_from_flow_and_depth(
            good_old=good_old,
            good_new=good_new,
            depth_map=depth_map,
            dt=dt,
        )

        # Low-pass filter to reduce frame-to-frame jumps.
        filtered_vx_mps = self.vel_alpha * raw_vx_mps + (1.0 - self.vel_alpha) * self.prev_vx
        filtered_vy_mps = self.vel_alpha * raw_vy_mps + (1.0 - self.vel_alpha) * self.prev_vy
        filtered_vz_mps = self.vel_alpha * raw_vz_mps + (1.0 - self.vel_alpha) * self.prev_vz

        self.prev_vx = filtered_vx_mps
        self.prev_vy = filtered_vy_mps
        self.prev_vz = filtered_vz_mps

        # Dead band to suppress tiny noise in the published velocity.
        vx_mps = filtered_vx_mps
        vy_mps = filtered_vy_mps
        vz_mps = filtered_vz_mps

        if abs(vx_mps) < 0.02:
            vx_mps = 0.0
        if abs(vy_mps) < 0.2:
            vy_mps = 0.0
        if abs(vz_mps) < 0.2:
            vz_mps = 0.0

        vel_msg = Vector3Stamped()
        vel_msg.header.stamp = rgb_stamp
        vel_msg.header.frame_id = self.camera_frame
        vel_msg.vector.x = float(vx_mps)
        vel_msg.vector.y = float(vy_mps)
        vel_msg.vector.z = float(vz_mps)
        self.vel_pub.publish(vel_msg)

        self.published_count += 1

        rgb_stamp_sec = flow_item["rgb_stamp_sec"]
        self.vel_csv_writer.writerow([
            f"{rgb_stamp_sec:.6f}", f"{dt:.4f}",
            #f"{raw_vx_mps:.4f}", f"{raw_vy_mps:.4f}", f"{raw_vz_mps:.4f}",
            #f"{filtered_vx_mps:.4f}", f"{filtered_vy_mps:.4f}", f"{filtered_vz_mps:.4f}",
            f"{vx_mps:.4f}", f"{vy_mps:.4f}", f"{vz_mps:.4f}",
            n_used
        ])
        self.vel_log_file.flush()  # Ensure data is written to disk promptly


        self.print_velocity_estimate(
            flow_item=flow_item,
            match_age_sec=match_age_sec,
            depth_arrival_sec=depth_arrival_sec,
            dt=dt,
            raw_vx_mps=raw_vx_mps,
            raw_vy_mps=raw_vy_mps,
            raw_vz_mps=raw_vz_mps,
            filtered_vx_mps=filtered_vx_mps,
            filtered_vy_mps=filtered_vy_mps,
            filtered_vz_mps=filtered_vz_mps,
            published_vx_mps=vx_mps,
            published_vy_mps=vy_mps,
            published_vz_mps=vz_mps,
            n_used=n_used,
        )

        if self.show_debug and flow_item.get("frame") is not None:
            self.draw_visual_debug(
                frame=flow_item["frame"],
                good_old=good_old,
                good_new=good_new,
                depth_map=depth_map,
                vx_mps=vx_mps,
                vy_mps=vy_mps,
                vz_mps=vz_mps,
                n_used=n_used,
                match_age_sec=match_age_sec,
                depth_stamp_sec=depth_stamp_sec,
                depth_arrival_sec=depth_arrival_sec,
            )


    def print_velocity_estimate(
        self,
        flow_item: Dict[str, Any],
        match_age_sec: float,
        depth_arrival_sec: float,
        dt: float,
        raw_vx_mps: float,
        raw_vy_mps: float,
        raw_vz_mps: float,
        filtered_vx_mps: float,
        filtered_vy_mps: float,
        filtered_vz_mps: float,
        published_vx_mps: float,
        published_vy_mps: float,
        published_vz_mps: float,
        n_used: int,
    ):
        """
        Text-only debug tool for velocity estimation.

        This replaces the need to use show_debug=True when you only want to see
        the estimated velocity and synchronization quality in the terminal.
        """
        if not self.print_velocity_debug:
            return

        if self.published_count % self.velocity_debug_every_n != 0:
            return

        rgb_arrival_to_depth_arrival = depth_arrival_sec - flow_item["rgb_arrival_sec"]

        raw_speed = math.sqrt(raw_vx_mps**2 + raw_vy_mps**2 + raw_vz_mps**2)
        filtered_speed = math.sqrt(
            filtered_vx_mps**2 + filtered_vy_mps**2 + filtered_vz_mps**2
        )
        published_speed = math.sqrt(
            published_vx_mps**2 + published_vy_mps**2 + published_vz_mps**2
        )

        self.get_logger().info(
            "\n"
            f"[VelocityDebug #{self.published_count}]\n"
            f"  sync_time_mode      : {self.sync_time_mode}\n"
            f"  flow_dt             : {dt:.4f} sec\n"
            f"  depth_after_flow    : {match_age_sec * 1000.0:.1f} ms\n"
            f"  arrival_latency     : {rgb_arrival_to_depth_arrival * 1000.0:.1f} ms\n"
            f"  pending_flow_queue  : {len(self.pending_flow_queue)}\n"
            f"  features_used       : {n_used}\n"
            f"  center_depth        : {self.center_depth:.3f} m\n"
            f"  raw_velocity        : vx={raw_vx_mps:+.4f}, vy={raw_vy_mps:+.4f}, vz={raw_vz_mps:+.4f}, |v|={raw_speed:.4f} m/s\n"
            f"  filtered_velocity   : vx={filtered_vx_mps:+.4f}, vy={filtered_vy_mps:+.4f}, vz={filtered_vz_mps:+.4f}, |v|={filtered_speed:.4f} m/s\n"
            f"  published_velocity  : vx={published_vx_mps:+.4f}, vy={published_vy_mps:+.4f}, vz={published_vz_mps:+.4f}, |v|={published_speed:.4f} m/s"
        )

    # ============================================================
    # Depth utilities
    # ============================================================
    def smooth_depth_map(self, raw_depth_map: np.ndarray) -> np.ndarray:
        raw_depth_map = raw_depth_map.astype(np.float32)

        if self.last_smoothed_depth is None:
            self.last_smoothed_depth = raw_depth_map
        elif self.last_smoothed_depth.shape != raw_depth_map.shape:
            self.get_logger().warn(
                "[Depth] Depth shape changed, resetting EMA smoothing buffer"
            )
            self.last_smoothed_depth = raw_depth_map
        else:
            self.last_smoothed_depth = (
                self.ema_alpha * raw_depth_map
                + (1.0 - self.ema_alpha) * self.last_smoothed_depth
            )

        return self.last_smoothed_depth.astype(np.float32)

    def update_center_depth(self, depth_map: np.ndarray):
        if self.cx is None or self.cy is None:
            return

        H, W = depth_map.shape[:2]
        u_idx = int(round(self.cx))
        v_idx = int(round(self.cy))

        if not (0 <= u_idx < W and 0 <= v_idx < H):
            return

        half_side = 2
        x0 = max(0, u_idx - half_side)
        x1 = min(W, u_idx + half_side + 1)
        y0 = max(0, v_idx - half_side)
        y1 = min(H, v_idx + half_side + 1)

        center_region = depth_map[y0:y1, x0:x1]
        valid_center_depths = center_region[
            np.isfinite(center_region) & (center_region > 0)
        ]

        if valid_center_depths.size > 0:
            self.center_depth = float(np.mean(valid_center_depths) * self.depth_scale)

    # ============================================================
    # Metric velocity from optical flow + depth
    # ============================================================
    def velocity_from_flow_and_depth(self, good_old, good_new, depth_map, dt: float):
        """
        Estimate metric velocity from pixel optical flow and depth.

        Returns:
            vx, vy, vz, n_used

        The final axis convention is kept from your existing implementation:
            return Vz_o, -Vx_o, -Vy_o
        """
        if dt <= 0.0:
            return 0.0, 0.0, 0.0, 0

        H, W = depth_map.shape[:2]

        du = (good_new[:, 0] - good_old[:, 0]) / dt
        dv = (good_new[:, 1] - good_old[:, 1]) / dt

        u_int = np.rint(good_new[:, 0]).astype(np.int32)
        v_int = np.rint(good_new[:, 1]).astype(np.int32)

        valid = (
            (u_int >= 0) & (u_int < W) &
            (v_int >= 0) & (v_int < H)
        )

        if not np.any(valid):
            return 0.0, 0.0, 0.0, 0

        Z = np.zeros_like(du, dtype=np.float32)
        Z[valid] = depth_map[v_int[valid], u_int[valid]] * self.depth_scale

        valid = (
            valid &
            np.isfinite(Z) &
            (Z > self.min_depth) &
            (Z < self.max_depth)
        )

        nv = int(np.sum(valid))
        if nv < 8:
            return 0.0, 0.0, 0.0, nv

        u_c_v = good_old[valid, 0].astype(np.float64) - float(self.cx)
        v_c_v = good_old[valid, 1].astype(np.float64) - float(self.cy)

        Zv = Z[valid].astype(np.float64)
        du_v = du[valid].astype(np.float64)
        dv_v = dv[valid].astype(np.float64)

        #  Outlier Rejection use RANSAC 
        vx_estimates = - (du_v * Zv) / float(self.fx)
        vy_estimates = - (dv_v * Zv) / float(self.fy)

        median_vx = np.median(vx_estimates)
        median_vy = np.median(vy_estimates)

        dev_x = np.abs(vx_estimates - median_vx)
        dev_y = np.abs(vy_estimates - median_vy)

        threshold = 0.3  # Tunable threshold for outlier rejection
        good_inliers = (dev_x < threshold) & (dev_y < threshold)

        nv_inliers = int(np.sum(good_inliers))
        if nv_inliers < 8:
            return 0.0, 0.0, 0.0, 0

        u_c_v_in = u_c_v[good_inliers]
        v_c_v_in = v_c_v[good_inliers]
        Zv_in = Zv[good_inliers]
        du_v_in = du_v[good_inliers]
        dv_v_in = dv_v[good_inliers]



        A = np.zeros((2 * nv_inliers, 3), dtype=np.float64)
        B = np.zeros((2 * nv_inliers,), dtype=np.float64)

        A[0::2, 0] = -float(self.fx)
        A[0::2, 2] = u_c_v_in
        B[0::2] = du_v_in * Zv_in

        A[1::2, 1] = -float(self.fy)
        A[1::2, 2] = v_c_v_in
        B[1::2] = dv_v_in * Zv_in

        dist_sq = u_c_v_in**2 + v_c_v_in**2
        denom = 0.05 * (float(self.cx) ** 2 + float(self.cy) ** 2)
        weights = np.exp(-dist_sq / max(denom, 1e-9))

        W_vec = np.zeros((2 * nv_inliers,), dtype=np.float64)
        W_vec[0::2] = weights
        W_vec[1::2] = weights
        sqrt_w = np.sqrt(W_vec)

        try:
            vel, *_ = np.linalg.lstsq(
                A * sqrt_w[:, np.newaxis],
                B * sqrt_w,
                rcond=None,
            )
        except np.linalg.LinAlgError:
            return 0.0, 0.0, 0.0, nv_inliers

        Vx_o = float(vel[0])
        Vy_o = float(vel[1])
        Vz_o = float(vel[2])

        return Vz_o, -Vx_o, -Vy_o, nv_inliers

    # ============================================================
    # Extra callbacks
    # ============================================================
    def gt_vel_callback(self, msg: Twist):
        self.latest_gt_vx = msg.linear.x
        self.latest_gt_vy = msg.linear.y
        self.latest_gt_vz = msg.linear.z

    def pose_est_callback(self, msg: PoseStamped):
        x = msg.pose.position.x
        y = msg.pose.position.y
        z = msg.pose.position.z

        self.debug_path.append((x, y))
        self.current_distance = math.sqrt(x**2 + y**2 + z**2)

        self.trajectory_history.append({
            "image": f"frame_{len(self.trajectory_history):06d}.jpg",
            "pose": {
                "x": float(x),
                "y": float(y),
                "z": float(z),
                "yaw": 0.0,
            },
        })

        stamp_sec = self.stamp_to_sec(msg.header.stamp)
        self.pose_csv_writer.writerow([
            f"{stamp_sec:.6f}", 
            f"{x:.4f}", f"{y:.4f}", f"{z:.4f}"
        ])
        self.pose_log_file.flush()

    # ============================================================
    # Debug drawing
    # ============================================================
    def draw_visual_debug(
        self,
        frame,
        good_old,
        good_new,
        depth_map,
        vx_mps,
        vy_mps,
        vz_mps,
        n_used,
        match_age_sec,
        depth_stamp_sec,
        depth_arrival_sec,
    ):
        vis = frame.copy()
        self.draw_debug(vis, good_old, good_new, depth_map)
        self.draw_minimap(vis, self.debug_path)

        cv2.putText(
            vis,
            f"vx={vx_mps:.3f} vy={vy_mps:.3f} vz={vz_mps:.3f} used={n_used}",
            (10, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 0, 0),
            2,
        )

        cv2.putText(
            vis,
            f"Depth-Flow match age: {match_age_sec * 1000.0:.1f} ms",
            (10, 65),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (0, 255, 255),
            2,
        )

        cv2.putText(
            vis,
            f"Center depth: {self.center_depth:.2f} m",
            (10, 100),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 100, 0),
            2,
        )

        cv2.putText(
            vis,
            f"Distance: {self.current_distance:.2f} m",
            (10, 135),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.9,
            (0, 255, 0),
            2,
        )

        cv2.imshow("Flow now, Depth later", vis)
        cv2.waitKey(1)

    def draw_debug(self, vis_bgr, good_old, good_new, depth_map):
        H, W = depth_map.shape[:2]

        for (u2, v2), (u1, v1) in zip(good_new, good_old):
            x2 = int(round(u2))
            y2 = int(round(v2))
            x1 = int(round(u1))
            y1 = int(round(v1))

            if not (0 <= x2 < W and 0 <= y2 < H):
                continue

            z = float(depth_map[y2, x2])
            if np.isfinite(z):
                cv2.arrowedLine(
                    vis_bgr,
                    (x1, y1),
                    (x2, y2),
                    (0, 0, 255),
                    2,
                    tipLength=0.3,
                )

    def draw_minimap(self, vis, path):
        if len(path) < 2:
            return

        map_size = 200
        margin = 15
        h, w = vis.shape[:2]

        overlay = vis.copy()
        cv2.rectangle(
            overlay,
            (w - map_size - margin, margin),
            (w - margin, margin + map_size),
            (0, 0, 0),
            -1,
        )
        cv2.addWeighted(overlay, 0.6, vis, 0.4, 0, vis)

        xs = [p[0] for p in path]
        ys = [p[1] for p in path]

        min_x = min(xs)
        max_x = max(xs)
        min_y = min(ys)
        max_y = max(ys)

        span = max(max_x - min_x, max_y - min_y, 1.0)
        scale = (map_size - 40) / span

        cx = (min_x + max_x) / 2.0
        cy = (min_y + max_y) / 2.0

        screen_cx = w - margin - map_size // 2
        screen_cy = margin + map_size // 2

        pts = []
        for px, py in path:
            mx = int(screen_cx - (py - cy) * scale)
            my = int(screen_cy - (px - cx) * scale)
            pts.append((mx, my))

        for i in range(1, len(pts)):
            cv2.line(vis, pts[i - 1], pts[i], (0, 255, 255), 2)

        cv2.circle(vis, pts[0], 4, (0, 255, 0), -1)
        cv2.circle(vis, pts[-1], 6, (0, 0, 255), -1)

        cv2.putText(
            vis,
            "Trajectory Map",
            (w - map_size - margin + 10, margin + 25),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            (255, 255, 255),
            1,
        )

    # ============================================================
    # Shutdown tasks: save trajectory history to JSON
    # ============================================================
    def destroy_node(self):
        
        if hasattr(self, 'vel_log_file') and not self.vel_log_file.closed:
            self.vel_log_file.close()
            self.get_logger().info(f"[CSV] Saved velocity log to {self.vel_csv_path}")
            
        if hasattr(self, 'pose_log_file') and not self.pose_log_file.closed:
            self.pose_log_file.close()
            self.get_logger().info(f"[CSV] Saved pose log to {self.pose_csv_path}")

        if self.trajectory_history:
            try:
                with open(self.json_out_path, "w", encoding="utf-8") as f:
                    json.dump(self.trajectory_history, f, indent=4)
                self.get_logger().info(
                    f"[JSON] Saved {len(self.trajectory_history)} poses to {self.json_out_path}"
                )
            except Exception as e:
                self.get_logger().error(f"Failed to save JSON: {e}")

        super().destroy_node()


def main():
    rclpy.init()
    node = FlowDepthVelocityNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    node.destroy_node()
    cv2.destroyAllWindows()

    if rclpy.ok():
        rclpy.shutdown()


if __name__ == "__main__":
    main()