# the drone is located at the origin (0, 0, 1) , in 4.5 meters there is a wall with tag 12, in the end of the hallway.
tags:

 # Door towards the exit, the first one
  5:
    xyz: [4.5, 0, 1.33]
    rpy: [-1.5708, 0, -1.5708]
    size: 0.29


# Communication room
  2:
    xyz: [2.55, -2.3, 0.97]
    rpy: [-1.5708, 0,  -3.1416]
    size: 0.2

# Enter the hallway to the right towards the MAMAD, same orientation as tag 5
  10:
    xyz: [3.13, -0.82, 1.03]
    rpy: [-1.5708,  0, -1.5708]
    size: 0.2

 # hallway towards the comm room same orientation as tag 5, next to tag 10 - small version of tag 8
  8:
    xyz: [3.13, -1.75, 1.03]
    rpy: [-1.5708, 0, -1.5708]
    size: 0.15

 # MAMAD Door
  3:
    xyz: [1.45, -2.07, 1.07]
    rpy: [-1.5708, 0, -3.1416]
    size: 0.28

# on the wall
  7:
    xyz: [ 1.95, -0.92, 1.245 ]
    rpy: [-1.5708,  0, 1.5708]
    size: 0.195

#  inside MAMAD, in front of mamad's door facing the window
  6:
    xyz: [-0.245, -1.01, 1.35]
    rpy: [ -1.5708, 0, 0 ]
    size: 0.2

 # Inside the MAMAD, above the desk, facing the MAMAD's entrance
  9:
    xyz: [-1.55, -1.64, 1.11]
    rpy: [-1.5708,  0, 1.5708]
    size: 0.28

 # Below SPARX logo, currently near the fridge, below window. orientation like the MAMAD door --replaced with 8
  11:
    xyz: [0.15, -4.7, 1.0]
    rpy: [-1.5708,  0, -3.1416]
    size: 0.265

# on a cardboard box, below the desk, on a trash can
  14:
    xyz: [ -0.585, -1.16, 0.71 ]
    rpy: [-1.5708,  0, 1.5708]
    size: 0.265


 # inside the MAMAD, near the weapon, orientation like exit office door
  0:
    xyz: [1.50, -3.3, 1.15]
    rpy: [-1.5708, 0, -1.5708]
    size: 0.2

# # Inbal's Office
#  2:
#    xyz: [1.7, 0.75, 1.0]
#    rpy: [-1.5708, 0, 0]
#    size: 0.2


  # inside MAMAD, in front of mamad's door facing the window
#  7:
#    xyz: [ -0.25, -0.99, 1.23 ]
#    rpy: [ -1.5708, 0, 0 ]
#    size: 0.15

 # Tag 4, near the screen inside the MAMAD, same wall as tag 9

  4:
    xyz: [-1.55, -3.49, 1.36]
    rpy: [-1.5708,  0, 1.5708]
    size: 0.20
