#!/usr/bin/env python3
"""
Interactive Navigation Pipeline
================================
UI & orchestration layer — ALL algorithms live in sparx_agency.core.

Flow:
  1. User selects a map
  2. Topology pipeline runs (inflate → SDF → Voronoi → rooms → room–object graph)
  3. User clicks to place the robot
  4. User types a natural-language navigation task
  5. LLM filters irrelevant objects, plans a route, returns instructions
  6. Loop back to step 3

Place at: sparx_agency/tasks/mapping/interactive_nav_pipeline.py

Requirements:
  - Ollama running locally with a model (default: llama3.1:8b)
  - Maps generated by generate_maps.py (in ./maps/ folder)
  - sparx_agency.core installed (mapping.costmap, mapping.topology)

NOTE — if running from PyCharm:
  Settings → Tools → Python Scientific → UNCHECK "Show plots in tool window"
"""

from __future__ import annotations

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0: Force interactive backend via env var — BEFORE any matplotlib import.
# This is the highest-priority mechanism and cannot be overridden by IDEs.
# ═══════════════════════════════════════════════════════════════════════════════
import os
os.environ.pop("MPLBACKEND", None)          # clear any IDE-injected value

_BACKEND_PREF = ["TkAgg", "Qt5Agg", "QtAgg"]

def _find_working_backend() -> str | None:
    """Probe which GUI backend is actually importable."""
    for b in _BACKEND_PREF:
        if b == "TkAgg":
            try:
                import tkinter       # noqa: F401
                return b
            except ImportError:
                continue
        elif b in ("Qt5Agg", "QtAgg"):
            try:
                from PyQt5 import QtWidgets   # noqa: F401
                return b
            except ImportError:
                continue
    return None

_chosen_backend = _find_working_backend()
if _chosen_backend is None:
    import sys
    print("⚠  ERROR: No interactive GUI backend available.")
    print("   Install one of:")
    print("     sudo apt install python3-tk")
    print("     pip install PyQt5")
    sys.exit(1)

os.environ["MPLBACKEND"] = _chosen_backend     # lock it in

# Now safe to import matplotlib
import matplotlib
matplotlib.use(_chosen_backend, force=True)

import json
import subprocess
import sys
import tempfile
import time
import types
from typing import Callable

# ═══════════════════════════════════════════════════════════════════════════════
# Project root — ensure sparx_agency is importable from terminal too.
# Script location: sparx_agency/tasks/mapping/topology/interactive_nav_pipeline.py
# Project root:    4 levels up
# ═══════════════════════════════════════════════════════════════════════════════

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "..", "..", ".."))

if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# ═══════════════════════════════════════════════════════════════════════════════
# ROS stubs — let us import sparx_agency.core without a ROS workspace
# ═══════════════════════════════════════════════════════════════════════════════

class _RosStub(types.ModuleType):
    """Module stub that returns a dummy for any attribute access."""
    def __getattr__(self, name):
        return type(name, (), {"__init__": lambda *a, **k: None})

for _mod in [
    "sensor_msgs", "sensor_msgs.msg",
    "std_msgs", "std_msgs.msg",
    "nav_msgs", "nav_msgs.msg",
    "geometry_msgs", "geometry_msgs.msg",
    "rospy", "rclpy", "rclpy.node",
    "cv_bridge", "tf2_ros",
]:
    sys.modules.setdefault(_mod, _RosStub(_mod))

# ═══════════════════════════════════════════════════════════════════════════════
# Core imports — ALL algorithmic logic lives here
# ═══════════════════════════════════════════════════════════════════════════════

import matplotlib.pyplot as plt

import networkx as nx
import numpy as np
from matplotlib.patches import Rectangle

# ═══════════════════════════════════════════════════════════════════════════════
# Direct tkinter window — bypasses plt.show() entirely.
# PyCharm Scientific Mode can only intercept plt.show(); it cannot
# intercept a raw tkinter window with an embedded matplotlib canvas.
# ═══════════════════════════════════════════════════════════════════════════════

import tkinter as tk
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure


def _show_figure_interactive(fig, title: str = "Figure", on_click=None):
    """
    Display a matplotlib Figure in a real tkinter window.
    Blocks until the user closes the window.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
    title : str        Window title
    on_click : callable or None
        If given, connected as a button_press_event callback.
        When on_click calls root.quit(), the window closes.
    """
    root = tk.Tk()
    root.title(title)
    root.protocol("WM_DELETE_WINDOW", root.quit)

    canvas = FigureCanvasTkAgg(fig, master=root)
    canvas.draw()
    canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)

    toolbar = NavigationToolbar2Tk(canvas, root)
    toolbar.update()

    cid = None
    if on_click is not None:
        cid = canvas.mpl_connect("button_press_event",
                                  lambda event: on_click(event, fig, canvas, root))

    root.mainloop()

    if cid is not None:
        canvas.mpl_disconnect(cid)

    try:
        root.destroy()
    except tk.TclError:
        pass  # already destroyed


print(f"[matplotlib backend: direct tkinter (FigureCanvasTkAgg)]")

# --- Costmap pipeline ---
from sparx_agency.core.mapping.costmap.inflation import inflate_occupancy, InflationParams
from sparx_agency.core.mapping.costmap.sdf import compute_sdf, boundary_cost_field

# --- Topology pipeline ---
from sparx_agency.core.mapping.topology import (
    extract_voronoi_graph, TopologyParams,
    get_junctions, get_dead_ends,
    separate_rooms, DoorInfo, RoomSeparationParams,
    ObjectInfo, NodeType,
    assign_objects_to_rooms, build_room_object_graph,
    get_room_nodes, get_objects_in_room,
)

# --- LLM navigation planner ---
from sparx_agency.core.mapping.topology.llm_nav_planner import (
    NavPlanner,
    _room_object_dict, _robot_room,
)

# ═══════════════════════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════════════════════

_MAPS_DIR   = os.path.join(_SCRIPT_DIR, "maps")
RESOLUTION  = 0.05   # 5 cm per cell (matches generate_maps.py)


# ═══════════════════════════════════════════════════════════════════════════════
# Map loading — parse JSON into core data structures
# ═══════════════════════════════════════════════════════════════════════════════

def discover_maps() -> list[str]:
    """Return sorted list of available map folder names."""
    if not os.path.isdir(_MAPS_DIR):
        return []
    return sorted(
        d for d in os.listdir(_MAPS_DIR)
        if os.path.isfile(os.path.join(_MAPS_DIR, d, "occupancy.npy"))
    )


def load_map(name: str) -> tuple[np.ndarray, list[ObjectInfo], list[DoorInfo], dict]:
    """
    Load a map from disk.

    Returns
    -------
    occ : np.ndarray          uint8 occupancy grid
    objects : list[ObjectInfo] objects with position/bbox (no room_id yet)
    doors : list[DoorInfo]     door openings
    meta : dict                metadata dict
    """
    map_dir = os.path.join(_MAPS_DIR, name)

    occ = np.load(os.path.join(map_dir, "occupancy.npy"))

    with open(os.path.join(map_dir, "objects.json")) as f:
        raw_objs = json.load(f)
    objects = [
        ObjectInfo(
            name=o["name"],
            position=np.array(o["position"]),
            bbox=tuple(o["bbox"]),
            semantic_class=o["semantic_class"],
        )
        for o in raw_objs
    ]

    with open(os.path.join(map_dir, "doors.json")) as f:
        raw_doors = json.load(f)
    doors = [
        DoorInfo(
            position=np.array(d["position"]),
            size=np.array(d["size"]),
        )
        for d in raw_doors
    ]

    with open(os.path.join(map_dir, "metadata.json")) as f:
        meta = json.load(f)

    return occ, objects, doors, meta


# ═══════════════════════════════════════════════════════════════════════════════
# Topology pipeline runner — calls core algorithms
# ═══════════════════════════════════════════════════════════════════════════════

class PipelineResult:
    """Container for all topology pipeline outputs."""
    __slots__ = (
        "occ", "inflated", "sdf", "cost",
        "G_voronoi", "G_separated", "door_field",
        "objects", "doors", "rog",
    )

def run_topology_pipeline(
    occ: np.ndarray,
    objects: list[ObjectInfo],
    doors: list[DoorInfo],
) -> PipelineResult:
    """
    Run the full topology pipeline using core algorithms.
    No algorithmic code here — only orchestration and timing.
    """
    res = PipelineResult()
    res.occ = occ
    res.objects = objects
    res.doors = doors

    # Step 1: Inflation
    print("  [1/6] Inflating occupancy...")
    t0 = time.perf_counter()
    res.inflated = inflate_occupancy(
        occ, resolution=RESOLUTION,
        params=InflationParams(radius_m=0.15),
    )
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms")

    # Step 2: SDF
    print("  [2/6] Computing SDF...")
    t0 = time.perf_counter()
    res.sdf = compute_sdf(res.inflated, resolution=RESOLUTION)
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms")

    # Step 3: Boundary cost field
    print("  [3/6] Computing boundary cost field...")
    t0 = time.perf_counter()
    res.cost = boundary_cost_field(
        res.inflated, resolution=RESOLUTION, distance_scale_m=1.5,
    )
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms")

    # Step 4: Voronoi topology graph
    print("  [4/6] Extracting Voronoi graph...")
    t0 = time.perf_counter()
    res.G_voronoi = extract_voronoi_graph(
        res.inflated, resolution=RESOLUTION,
        params=TopologyParams(
            sdf_scale_m=1.5,
            inner_inflate_m=0.15,
            sparsify_dist_m=0.3,
            min_component=4,
        ),
    )
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms  |  "
          f"Nodes: {len(res.G_voronoi.nodes)}, Edges: {len(res.G_voronoi.edges)}")

    # Step 5: Room separation via doors
    print("  [5/6] Separating rooms...")
    t0 = time.perf_counter()
    res.G_separated, res.door_field = separate_rooms(
        res.G_voronoi,
        grid_shape=occ.shape,
        doors=doors,
        resolution=RESOLUTION,
        params=RoomSeparationParams(edge_score_threshold=0.05, min_component=4),
    )
    n_rooms = nx.number_connected_components(res.G_separated)
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms  |  Rooms: {n_rooms}")

    # Step 6: Assign objects to rooms & build room–object graph
    print("  [6/6] Building room–object graph...")
    t0 = time.perf_counter()
    assign_objects_to_rooms(objects, res.G_separated)
    res.rog = build_room_object_graph(res.G_separated, objects)
    print(f"         {(time.perf_counter()-t0)*1000:.1f} ms")

    return res


# ═══════════════════════════════════════════════════════════════════════════════
# Visualization helpers — display-only, no algorithms
# ═══════════════════════════════════════════════════════════════════════════════

def _room_colors(n: int):
    """Generate n distinct room colors."""
    return plt.cm.Set2(np.linspace(0, 1, max(n, 1)))


def plot_pipeline_summary(res: PipelineResult, map_name: str):
    """Show a 2×3 summary of pipeline stages."""
    fig = Figure(figsize=(20, 11))
    axes = fig.subplots(2, 3)
    fig.suptitle(f"Topology Pipeline — {map_name}", fontsize=14, fontweight="bold")
    occ, inflated = res.occ, res.inflated

    # 1. Raw occupancy
    axes[0, 0].imshow(occ != 0, cmap="gray_r", interpolation="nearest")
    axes[0, 0].set_title("1. Raw Occupancy")
    axes[0, 0].set_axis_off()

    # 2. Inflated
    rgb = np.ones((*inflated.shape, 3))
    rgb[inflated != 0] = [1.0, 0.7, 0.7]
    rgb[occ != 0] = [0.0, 0.0, 0.0]
    axes[0, 1].imshow(rgb, interpolation="nearest")
    axes[0, 1].set_title("2. Inflated Occupancy")
    axes[0, 1].set_axis_off()

    # 3. SDF
    vmax = np.abs(res.sdf).max()
    im = axes[0, 2].imshow(res.sdf, cmap="RdBu", vmin=-vmax, vmax=vmax,
                            interpolation="nearest")
    fig.colorbar(im, ax=axes[0, 2], fraction=0.046, pad=0.04, label="meters")
    axes[0, 2].set_title("3. Signed Distance Field")
    axes[0, 2].set_axis_off()

    # 4. Voronoi graph
    _draw_voronoi(axes[1, 0], occ, inflated, res.G_voronoi, "4. Voronoi Graph")

    # 5. Room separation
    _draw_rooms(axes[1, 1], occ, inflated, res.G_separated, "5. Room Separation")

    # 6. Room–object graph
    _draw_room_objects(axes[1, 2], occ, inflated, res.G_separated,
                       res.rog, res.objects, "6. Room–Object Graph")

    fig.tight_layout()
    _show_figure_interactive(fig, title=f"Pipeline — {map_name}")
    return fig


def _draw_voronoi(ax, occ, inflated, G, title):
    rgb = np.ones((*occ.shape, 3)) * 0.95
    rgb[inflated != 0] = [0.85, 0.85, 0.85]
    rgb[occ != 0] = [0.2, 0.2, 0.2]
    ax.imshow(rgb, interpolation="nearest")

    if len(G.nodes) == 0:
        ax.set_title(f"{title} (empty)")
        ax.set_axis_off()
        return

    junctions = set(get_junctions(G))
    dead_ends = set(get_dead_ends(G))
    passthrough = set(G.nodes) - junctions - dead_ends

    for u, v in G.edges():
        ax.plot([u[1], v[1]], [u[0], v[0]], color="#4488cc", lw=0.6, alpha=0.7)

    def _scatter(nodes, c, s, label):
        if nodes:
            arr = np.array(list(nodes))
            ax.scatter(arr[:, 1], arr[:, 0], c=c, s=s, zorder=5,
                       label=label, edgecolors="none")

    _scatter(passthrough, "#4488cc", 3, f"Pass-through [{len(passthrough)}]")
    _scatter(junctions, "#ff3333", 30, f"Junctions [{len(junctions)}]")
    _scatter(dead_ends, "#33cc33", 18, f"Dead-ends [{len(dead_ends)}]")

    ax.legend(loc="upper right", fontsize=6, framealpha=0.9)
    ax.set_title(title)
    ax.set_axis_off()


def _draw_rooms(ax, occ, inflated, G_sep, title):
    rgb = np.ones((*occ.shape, 3)) * 0.95
    rgb[inflated != 0] = [0.85, 0.85, 0.85]
    rgb[occ != 0] = [0.2, 0.2, 0.2]
    ax.imshow(rgb, interpolation="nearest")

    components = list(nx.connected_components(G_sep))
    cmap = _room_colors(len(components))
    for ci, comp in enumerate(components):
        color = cmap[ci % len(cmap)][:3]
        sub = G_sep.subgraph(comp)
        for u, v in sub.edges():
            ax.plot([u[1], v[1]], [u[0], v[0]], color=color, lw=1.0, alpha=0.8)
        arr = np.array(list(comp))
        ax.scatter(arr[:, 1], arr[:, 0], c=[color], s=6, zorder=5,
                   label=f"Room {ci}", edgecolors="none")

    ax.legend(loc="upper right", fontsize=6, framealpha=0.9)
    ax.set_title(title)
    ax.set_axis_off()


def _draw_room_objects(ax, occ, inflated, G_sep, rog, objects, title):
    rgb = np.ones((*occ.shape, 3)) * 0.95
    rgb[inflated != 0] = [0.90, 0.90, 0.90]
    rgb[occ != 0] = [0.2, 0.2, 0.2]
    ax.imshow(rgb, interpolation="nearest")

    components = list(nx.connected_components(G_sep))
    cmap = _room_colors(len(components))

    # Room Voronoi edges
    for ci, comp in enumerate(components):
        color = cmap[ci % len(cmap)][:3]
        sub = G_sep.subgraph(comp)
        for u, v in sub.edges():
            ax.plot([u[1], v[1]], [u[0], v[0]], color=color, lw=0.5, alpha=0.35)

    # Room centre stars
    for rname in get_room_nodes(rog):
        rd = rog.nodes[rname]
        rc, cc = rd["pos_map"]
        color = cmap[rd["room_id"] % len(cmap)][:3]
        ax.plot(cc, rc, marker="*", color=color, markersize=14,
                markeredgecolor="k", markeredgewidth=0.5, zorder=7)
        ax.annotate(rname, (cc, rc), fontsize=7, fontweight="bold",
                    color=color, ha="left", va="bottom",
                    xytext=(4, 4), textcoords="offset points")

    # Object markers
    for obj in objects:
        if obj.room_id is None or obj.room_id < 0:
            continue
        color = cmap[obj.room_id % len(cmap)][:3]
        r, c = obj.position
        ax.plot(c, r, "o", color=color, markersize=7,
                markeredgecolor="k", markeredgewidth=0.6, zorder=6)
        ax.annotate(obj.name, (c, r), fontsize=5, ha="left", va="top",
                    color="k", xytext=(3, -3), textcoords="offset points")

    ax.set_title(title)
    ax.set_axis_off()


def show_interactive_map(res: PipelineResult, map_name: str,
                         robot_pos: tuple | None = None):
    """
    Build the room–object map for robot placement.
    Returns (fig, ax) — Figure is not displayed yet.
    """
    fig = Figure(figsize=(12, 8))
    ax = fig.add_subplot(111)
    fig.suptitle(f"{map_name} — Click to place the robot",
                 fontsize=13, fontweight="bold")

    occ, inflated = res.occ, res.inflated
    G_sep, rog, objects = res.G_separated, res.rog, res.objects

    rgb = np.ones((*occ.shape, 3)) * 0.95
    rgb[inflated != 0] = [0.90, 0.90, 0.90]
    rgb[occ != 0] = [0.2, 0.2, 0.2]
    ax.imshow(rgb, interpolation="nearest")

    components = list(nx.connected_components(G_sep))
    cmap = _room_colors(len(components))

    # Room edges (thin)
    for ci, comp in enumerate(components):
        color = cmap[ci % len(cmap)][:3]
        sub = G_sep.subgraph(comp)
        for u, v in sub.edges():
            ax.plot([u[1], v[1]], [u[0], v[0]], color=color, lw=0.4, alpha=0.3)

    # Room centre stars + labels
    for rname in get_room_nodes(rog):
        rd = rog.nodes[rname]
        rc, cc = rd["pos_map"]
        color = cmap[rd["room_id"] % len(cmap)][:3]
        ax.plot(cc, rc, marker="*", color=color, markersize=16,
                markeredgecolor="k", markeredgewidth=0.5, zorder=7)
        ax.annotate(rname, (cc, rc), fontsize=8, fontweight="bold",
                    color=color, ha="left", va="bottom",
                    xytext=(5, 5), textcoords="offset points",
                    bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.7))

    # Objects
    for obj in objects:
        if obj.room_id is None or obj.room_id < 0:
            continue
        color = cmap[obj.room_id % len(cmap)][:3]
        r, c = obj.position
        ax.plot(c, r, "o", color=color, markersize=6,
                markeredgecolor="k", markeredgewidth=0.5, zorder=6)
        ax.annotate(obj.name, (c, r), fontsize=5.5, ha="left", va="top",
                    color="k", xytext=(3, -3), textcoords="offset points")

    # Robot marker (if already placed)
    if robot_pos is not None:
        rr, rc = robot_pos
        ax.plot(rc, rr, "D", color="red", markersize=14,
                markeredgecolor="white", markeredgewidth=2, zorder=10)
        ax.annotate("ROBOT", (rc, rr), fontsize=8, fontweight="bold",
                    color="red", ha="center", va="bottom",
                    xytext=(0, 10), textcoords="offset points")

    ax.set_axis_off()
    fig.tight_layout()
    return fig, ax


def show_navigation_result(res: PipelineResult, map_name: str,
                           robot_pos: tuple, task: str,
                           instructions: str, rog_pruned: nx.DiGraph):
    """Display navigation result: map + robot + highlighted path info."""
    fig = Figure(figsize=(18, 8))
    ax_map, ax_text = fig.subplots(1, 2, gridspec_kw={"width_ratios": [2, 1]})
    fig.suptitle(f"{map_name} — Navigation Result",
                 fontsize=13, fontweight="bold")

    occ, inflated = res.occ, res.inflated
    G_sep, rog, objects = res.G_separated, res.rog, res.objects

    # ── Left: map with robot ──
    rgb = np.ones((*occ.shape, 3)) * 0.95
    rgb[inflated != 0] = [0.90, 0.90, 0.90]
    rgb[occ != 0] = [0.2, 0.2, 0.2]
    ax_map.imshow(rgb, interpolation="nearest")

    components = list(nx.connected_components(G_sep))
    cmap = _room_colors(len(components))

    for ci, comp in enumerate(components):
        color = cmap[ci % len(cmap)][:3]
        sub = G_sep.subgraph(comp)
        for u, v in sub.edges():
            ax_map.plot([u[1], v[1]], [u[0], v[0]], color=color, lw=0.4, alpha=0.3)

    for rname in get_room_nodes(rog):
        rd = rog.nodes[rname]
        rc, cc = rd["pos_map"]
        color = cmap[rd["room_id"] % len(cmap)][:3]
        ax_map.plot(cc, rc, marker="*", color=color, markersize=14,
                    markeredgecolor="k", markeredgewidth=0.5, zorder=7)
        ax_map.annotate(rname, (cc, rc), fontsize=7, fontweight="bold",
                        color=color, ha="left", va="bottom",
                        xytext=(4, 4), textcoords="offset points",
                        bbox=dict(boxstyle="round,pad=0.2", fc="white", alpha=0.7))

    for obj in objects:
        if obj.room_id is None or obj.room_id < 0:
            continue
        color = cmap[obj.room_id % len(cmap)][:3]
        r, c = obj.position
        ax_map.plot(c, r, "o", color=color, markersize=6,
                    markeredgecolor="k", markeredgewidth=0.5, zorder=6)
        ax_map.annotate(obj.name, (c, r), fontsize=5, ha="left", va="top",
                        color="k", xytext=(3, -3), textcoords="offset points")

    # Robot
    rr, rc = robot_pos
    ax_map.plot(rc, rr, "D", color="red", markersize=14,
                markeredgecolor="white", markeredgewidth=2, zorder=10)
    ax_map.annotate("ROBOT", (rc, rr), fontsize=8, fontweight="bold",
                    color="red", ha="center", va="bottom",
                    xytext=(0, 10), textcoords="offset points")

    ax_map.set_axis_off()

    # ── Right: text panel ──
    ax_text.set_xlim(0, 1)
    ax_text.set_ylim(0, 1)
    ax_text.set_axis_off()

    # Task
    y = 0.95
    ax_text.text(0.05, y, "TASK:", fontsize=12, fontweight="bold",
                 va="top", transform=ax_text.transAxes)
    y -= 0.06
    ax_text.text(0.05, y, task, fontsize=10, va="top", style="italic",
                 wrap=True, transform=ax_text.transAxes)

    # Room hierarchy (from pruned graph)
    y -= 0.10
    ax_text.text(0.05, y, "ROOM–OBJECT MAP (after filtering):",
                 fontsize=11, fontweight="bold", va="top",
                 transform=ax_text.transAxes)
    y -= 0.05
    rod = _room_object_dict(rog_pruned)
    for rname in sorted(rod):
        ax_text.text(0.05, y, f"  ★ {rname}: {', '.join(rod[rname])}",
                     fontsize=8, va="top", family="monospace",
                     transform=ax_text.transAxes)
        y -= 0.04

    # Instructions
    y -= 0.04
    ax_text.text(0.05, y, "NAVIGATION INSTRUCTIONS:",
                 fontsize=11, fontweight="bold", va="top",
                 transform=ax_text.transAxes)
    y -= 0.05

    # Word-wrap instructions
    import textwrap
    wrapped = textwrap.fill(instructions, width=55)
    ax_text.text(0.05, y, wrapped, fontsize=9, va="top",
                 family="serif", transform=ax_text.transAxes,
                 bbox=dict(boxstyle="round,pad=0.4", fc="#f0f8ff",
                           ec="#4488cc", lw=1.2))

    fig.tight_layout()
    _show_figure_interactive(fig, title=f"Navigation — {map_name}")
    return fig


# ═══════════════════════════════════════════════════════════════════════════════
# Interactive UI helpers
# ═══════════════════════════════════════════════════════════════════════════════

def prompt_map_selection() -> str:
    """Terminal menu to pick a map."""
    maps = discover_maps()
    if not maps:
        print(f"ERROR: No maps found in {_MAPS_DIR}")
        print("       Run generate_maps.py first.")
        sys.exit(1)

    print("\n╔══════════════════════════════════════╗")
    print("║       AVAILABLE MAPS                 ║")
    print("╚══════════════════════════════════════╝")
    for i, name in enumerate(maps, 1):
        meta_path = os.path.join(_MAPS_DIR, name, "metadata.json")
        desc = ""
        if os.path.isfile(meta_path):
            with open(meta_path) as f:
                desc = json.load(f).get("description", "")
        print(f"  [{i}] {name}")
        if desc:
            print(f"      {desc}")
    print()

    while True:
        choice = input("Select a map (number): ").strip()
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(maps):
                return maps[idx]
        except ValueError:
            pass
        print(f"  Please enter a number between 1 and {len(maps)}.")


def click_robot_position(res: PipelineResult, map_name: str) -> tuple[float, float]:
    """
    Open an interactive tkinter window. User clicks to place the robot.
    Returns (row, col) in grid coordinates.
    """
    result = {"pos": None}

    fig, ax = show_interactive_map(res, map_name)

    def on_click(event, fig, canvas, root):
        if event.inaxes != ax:
            return
        col, row = event.xdata, event.ydata
        r, c = int(round(row)), int(round(col))

        # Reject clicks on occupied cells
        if r < 0 or r >= res.occ.shape[0] or c < 0 or c >= res.occ.shape[1]:
            print(f"  ✗ Position ({r}, {c}) is out of bounds.")
            return
        if res.occ[r, c] != 0 or res.inflated[r, c] != 0:
            print(f"  ✗ Position ({r}, {c}) is occupied — click on a free cell.")
            return

        result["pos"] = (r, c)
        # Draw robot marker
        ax.plot(c, r, "D", color="red", markersize=14,
                markeredgecolor="white", markeredgewidth=2, zorder=10)
        ax.annotate("ROBOT", (c, r), fontsize=8, fontweight="bold",
                    color="red", ha="center", va="bottom",
                    xytext=(0, 10), textcoords="offset points")
        canvas.draw()
        print(f"  ✓ Robot placed at row={r}, col={c}")

        # Close the window after a brief pause
        root.after(500, root.quit)

    print("\n  👆 Click on the map to place the robot...")
    print("     (click on a free white/light-grey cell)")
    _show_figure_interactive(fig, title=f"{map_name} — Click to place robot",
                             on_click=on_click)

    if result["pos"] is None:
        print("  ⚠ No position clicked — using map centre as fallback.")
        H, W = res.occ.shape
        result["pos"] = (H // 2, W // 2)

    return result["pos"]


def prompt_task() -> str:
    """Ask the user for a natural-language navigation task."""
    print()
    task = input("🗣️  Enter navigation task (e.g. 'find the oven'): ").strip()
    if not task:
        task = "find the refrigerator"
        print(f"   (empty input — using default: '{task}')")
    return task


# ═══════════════════════════════════════════════════════════════════════════════
# LLM backend — Ollama subprocess (UI concern, not core algorithm)
# ═══════════════════════════════════════════════════════════════════════════════

def ollama_backend(model: str = "llama3.1:8b") -> Callable[[str], str]:
    """Ollama LLM backend via subprocess."""

    # ── Connectivity test — fail fast if Ollama isn't running ──
    test = subprocess.run(
        "ollama list", shell=True, capture_output=True, text=True, timeout=10,
    )
    if test.returncode != 0:
        raise RuntimeError(
            f"Ollama is not running.\n"
            f"   Start it with:  ollama serve\n"
            f"   stderr: {test.stderr.strip()}"
        )

    # Verify the requested model is available
    if model not in test.stdout:
        print(f"   ⚠ Model '{model}' not found. Available models:")
        print(f"     {test.stdout.strip()}")
        print(f"   Pull it with:  ollama pull {model}")
        raise RuntimeError(f"Model '{model}' not available in Ollama.")

    def call(prompt: str) -> str:
        with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".txt") as f:
            f.write(prompt)
            tmp = f.name
        try:
            result = subprocess.run(
                f'cat "{tmp}" | ollama run {model}',
                shell=True, capture_output=True, text=True, timeout=180,
            )
            if result.returncode != 0:
                raise RuntimeError(f"Ollama error: {result.stderr.strip()}")
            return result.stdout.strip()
        finally:
            os.unlink(tmp)
    return call


# ═══════════════════════════════════════════════════════════════════════════════
# Print helpers
# ═══════════════════════════════════════════════════════════════════════════════

def print_room_hierarchy(rog: nx.DiGraph, objects: list[ObjectInfo]):
    """Pretty-print the room–object tree."""
    print("\n  Room–Object Hierarchy")
    print("  " + "=" * 45)
    for rname in sorted(get_room_nodes(rog)):
        rd = rog.nodes[rname]
        obj_names = get_objects_in_room(rog, rd["room_id"])
        print(f"    ★ {rname}  (centre: {rd['pos_map']})")
        if obj_names:
            for i, oname in enumerate(obj_names):
                od = rog.nodes[oname]
                branch = "├─" if i < len(obj_names) - 1 else "└─"
                print(f"      {branch} {oname:18s}  [{od['semantic_class']}]")
        else:
            print(f"      └─ (no objects)")
    print()


# ═══════════════════════════════════════════════════════════════════════════════
# Main interactive loop
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print("=" * 60)
    print("   INTERACTIVE NAVIGATION PIPELINE")
    print("=" * 60)

    # ── Step 1: Select & load map ──
    map_name = prompt_map_selection()
    print(f"\n📂 Loading map: {map_name}")
    occ, objects, doors, meta = load_map(map_name)
    print(f"   Grid: {occ.shape},  Objects: {len(objects)},  Doors: {len(doors)}")

    # ── Step 2: Run topology pipeline (one-time) ──
    print(f"\n⚙️  Running topology pipeline...")
    res = run_topology_pipeline(occ, objects, doors)

    # Print room hierarchy
    print_room_hierarchy(res.rog, res.objects)

    # Show pipeline summary
    print("📊 Showing pipeline summary (close the window to continue)...")
    plot_pipeline_summary(res, map_name)

    # ── Step 3: Set up LLM ──
    print("\n🤖 Connecting to Ollama LLM...")
    try:
        llm = ollama_backend("llama3.1:8b")
        planner = NavPlanner(llm_call=llm)
        print("   ✓ Ollama backend ready (model: llama3.1:8b)")
    except Exception as e:
        print(f"   ✗ {e}")
        print()
        print("   To fix:")
        print("     1. Open another terminal")
        print("     2. Run: ollama serve")
        print("     3. If model not pulled yet: ollama pull llama3.1:8b")
        print()
        print("   Continuing with dummy backend (no real LLM answers).")
        planner = NavPlanner(llm_call=lambda p: '{}')

    # ── Step 4: Interactive loop ──
    iteration = 0
    while True:
        iteration += 1
        print(f"\n{'━' * 60}")
        print(f"  ITERATION {iteration}")
        print(f"{'━' * 60}")

        # 4a. Place robot
        robot_pos = click_robot_position(res, map_name)
        robot_room = _robot_room(robot_pos, res.G_separated)
        print(f"   Robot is in: {robot_room}")

        # 4b. Get task
        task = prompt_task()

        # 4c. LLM Stage 1: Filter irrelevant objects
        print(f"\n🔍 [LLM Stage 1] Filtering objects for task: \"{task}\"...")
        try:
            rod_before = _room_object_dict(res.rog)
            rog_pruned = planner.filter_graph(res.rog, task)
            rod_after = _room_object_dict(rog_pruned)

            print("   Filtering results:")
            for room in sorted(rod_before):
                removed = set(rod_before[room]) - set(rod_after.get(room, []))
                kept = rod_after.get(room, [])
                line = f"     {room}: kept={kept}"
                if removed:
                    line += f"  removed={list(removed)}"
                print(line)

            # 4d. LLM Stage 2: Plan route & generate instructions
            print(f"\n🧭 [LLM Stage 2] Generating navigation instructions...")
            instructions = planner.plan_route(
                room_object_graph=rog_pruned,
                separated_graph=res.G_separated,
                robot_pos=robot_pos,
                task=task,
            )

            print(f"\n{'═' * 60}")
            print("  📍 NAVIGATION INSTRUCTIONS:")
            print(f"{'═' * 60}")
            print(f"  {instructions}")
            print(f"{'═' * 60}")

            # 4e. Show result on map
            show_navigation_result(res, map_name, robot_pos, task,
                                   instructions, rog_pruned)

        except Exception as e:
            print(f"\n  ❌ LLM error: {e}")
            print("     Make sure Ollama is running:  ollama serve")
            print("     Skipping to next iteration...")

        # 4f. Continue?
        print()
        again = input("🔄 New navigation query? [Y/n]: ").strip().lower()
        if again in ("n", "no", "q", "quit", "exit"):
            print("\n👋 Goodbye!")
            break


if __name__ == "__main__":
    main()